{
  "swagger" : "2.0",
  "info" : {
    "title" : "Tic Tac Toe Service APIs",
    "version" : "1.0",
    "description" : "Tic Tac Toe Service API is a sample document to illustrate various end-points and resources per OAS2 standards.",
    "contact" : {
      "name" : "Prakash Sinha",
      "url" : "https://github.com/prakashksinha/tic-tac-toe",
      "email" : "prakashksinha@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "prakashksinha.wordpress.com",
  "paths" : {
    "/games" : {
      "get" : {
        "operationId" : "findGames",
        "responses" : {
          "200" : {
            "description" : "Successfull",
            "schema" : {
              "$ref" : "#/definitions/game-partial-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "consequat"
              }
            }
          }
        },
        "summary" : "Find games by status",
        "tags" : [ "game" ],
        "security" : [ {
          "read-auth" : [ ]
        } ],
        "parameters" : [ {
          "in" : "query",
          "name" : "status",
          "type" : "string",
          "enum" : [ "started", "in progress", "ended" ],
          "description" : "Enumerated data type to get the list of games"
        } ],
        "description" : "Returns complete data set of games matching the status"
      },
      "post" : {
        "operationId" : "createGame",
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "schema" : {
            "$ref" : "#/definitions/game-complete-data"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/game-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "consequat",
                "name" : "ma",
                "moves" : [ {
                  "xPos" : 4,
                  "xPlayer" : {
                    "id" : "in"
                  },
                  "yPos" : 6,
                  "yPlayer" : {
                    "id" : "in enim dolor"
                  }
                }, {
                  "xPos" : 2,
                  "xPlayer" : {
                    "id" : "elit in sit ipsum"
                  },
                  "yPos" : 7,
                  "yPlayer" : {
                    "id" : "ullamco irure"
                  }
                } ],
                "result" : [ {
                  "winner" : {
                    "id" : "incididunt culpa"
                  },
                  "loser" : {
                    "id" : "ipsum dolore"
                  }
                }, {
                  "winner" : {
                    "id" : "ut commodo"
                  },
                  "loser" : {
                    "id" : "minim consequat et"
                  }
                }, {
                  "winner" : {
                    "id" : "ut"
                  },
                  "loser" : {
                    "id" : "minim in aliquip"
                  }
                }, {
                  "winner" : {
                    "id" : "nulla Excepteur tempor"
                  },
                  "loser" : {
                    "id" : "elit Duis"
                  }
                }, {
                  "winner" : {
                    "id" : "Lorem laborum cupidatat ut"
                  },
                  "loser" : {
                    "id" : "incididunt anim"
                  }
                } ],
                "status" : "ended",
                "session" : "https://y-i"
              }
            }
          }
        },
        "security" : [ {
          "write-auth" : [ ]
        } ],
        "tags" : [ "game" ],
        "summary" : "Creates the game object",
        "description" : "Used during the start of the game to create initial object"
      }
    },
    "/games/{id}" : {
      "parameters" : [ {
        "name" : "id",
        "in" : "path",
        "type" : "string",
        "required" : true
      } ],
      "get" : {
        "operationId" : "getGame",
        "responses" : {
          "200" : {
            "description" : "Successfull",
            "schema" : {
              "$ref" : "#/definitions/game-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "consequat",
                "name" : "ma",
                "moves" : [ {
                  "xPos" : 4,
                  "xPlayer" : {
                    "id" : "in"
                  },
                  "yPos" : 6,
                  "yPlayer" : {
                    "id" : "in enim dolor"
                  }
                }, {
                  "xPos" : 2,
                  "xPlayer" : {
                    "id" : "elit in sit ipsum"
                  },
                  "yPos" : 7,
                  "yPlayer" : {
                    "id" : "ullamco irure"
                  }
                } ],
                "result" : [ {
                  "winner" : {
                    "id" : "incididunt culpa"
                  },
                  "loser" : {
                    "id" : "ipsum dolore"
                  }
                }, {
                  "winner" : {
                    "id" : "ut commodo"
                  },
                  "loser" : {
                    "id" : "minim consequat et"
                  }
                }, {
                  "winner" : {
                    "id" : "ut"
                  },
                  "loser" : {
                    "id" : "minim in aliquip"
                  }
                }, {
                  "winner" : {
                    "id" : "nulla Excepteur tempor"
                  },
                  "loser" : {
                    "id" : "elit Duis"
                  }
                }, {
                  "winner" : {
                    "id" : "Lorem laborum cupidatat ut"
                  },
                  "loser" : {
                    "id" : "incididunt anim"
                  }
                } ],
                "status" : "ended",
                "session" : "https://y-i"
              }
            }
          }
        },
        "summary" : "Returns the game data",
        "description" : "Retrieves the full data set for the given game id",
        "tags" : [ "game" ],
        "security" : [ {
          "read-auth" : [ ]
        } ]
      },
      "put" : {
        "operationId" : "updateGame",
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "schema" : {
            "$ref" : "#/definitions/game-complete-data"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful",
            "schema" : {
              "$ref" : "#/definitions/game-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "consequat",
                "name" : "ma-updated",
                "moves" : [ {
                  "xPos" : 4,
                  "xPlayer" : {
                    "id" : "in"
                  },
                  "yPos" : 6,
                  "yPlayer" : {
                    "id" : "in enim dolor"
                  }
                }, {
                  "xPos" : 2,
                  "xPlayer" : {
                    "id" : "elit in sit ipsum"
                  },
                  "yPos" : 7,
                  "yPlayer" : {
                    "id" : "ullamco irure"
                  }
                } ],
                "result" : [ {
                  "winner" : {
                    "id" : "incididunt culpa"
                  },
                  "loser" : {
                    "id" : "ipsum dolore"
                  }
                }, {
                  "winner" : {
                    "id" : "ut commodo"
                  },
                  "loser" : {
                    "id" : "minim consequat et"
                  }
                }, {
                  "winner" : {
                    "id" : "ut"
                  },
                  "loser" : {
                    "id" : "minim in aliquip"
                  }
                }, {
                  "winner" : {
                    "id" : "nulla Excepteur tempor"
                  },
                  "loser" : {
                    "id" : "elit Duis"
                  }
                }, {
                  "winner" : {
                    "id" : "Lorem laborum cupidatat ut"
                  },
                  "loser" : {
                    "id" : "incididunt anim"
                  }
                } ],
                "status" : "ended",
                "session" : "https://y-i"
              }
            }
          }
        },
        "tags" : [ "game" ]
      },
      "delete" : {
        "operationId" : "deleteGame",
        "responses" : {
          "204" : {
            "description" : "Successfully deleted"
          }
        },
        "tags" : [ "game" ],
        "summary" : "Deletes the game",
        "description" : "Game with the passed id is logically marked for deletion",
        "security" : [ {
          "write-auth" : [ ]
        } ],
        "parameters" : [ {
          "in" : "path",
          "name" : "id",
          "type" : "string",
          "required" : true
        } ]
      }
    },
    "/players" : {
      "get" : {
        "operationId" : "findPlayers",
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/player-complete-data"
              }
            },
            "examples" : {
              "application/json" : [ {
                "id" : "ut commodo",
                "name" : "magna fugiat in aute officia",
                "email" : "joTDC3FEKT@toz.uwj",
                "password" : "elit",
                "createdOn" : "1940-12-30T21:33:07.821Z",
                "updatedOn" : "1948-08-09T19:56:06.657Z",
                "friends" : [ {
                  "id" : "minim veniam al"
                }, {
                  "id" : "cupidatat magna mollit sint"
                }, {
                  "id" : "dolore"
                }, {
                  "id" : "aliquip amet"
                } ]
              }, {
                "id" : "dolore irure",
                "name" : "ex nisi voluptate",
                "email" : "1IjE7HeMIOLGtuk@zZHeDqMqEqHKXZHPiqiwGm.nuvf",
                "password" : "nulla magna elit amet",
                "createdOn" : "1957-08-02T05:49:03.160Z",
                "updatedOn" : "1968-08-16T08:26:08.181Z",
                "friends" : [ {
                  "id" : "est"
                }, {
                  "id" : "eli"
                }, {
                  "id" : "irure ullamco sint"
                }, {
                  "id" : "ut irure"
                } ]
              }, {
                "id" : "ad fugiat nisi",
                "name" : "labore in officia",
                "email" : "5OY18Wdf8v@MofgZUgpHCzj.bv",
                "password" : "sed velit ut et",
                "createdOn" : "1958-03-24T12:35:18.704Z",
                "updatedOn" : "1984-09-29T03:27:39.402Z",
                "friends" : [ {
                  "id" : "dolore Excepteur"
                }, {
                  "id" : "consectetur eiusmod id dolor"
                }, {
                  "id" : "ipsum"
                }, {
                  "id" : "Ut irure"
                }, {
                  "id" : "esse qui tempor sint"
                } ]
              } ]
            }
          }
        },
        "tags" : [ "player" ]
      },
      "post" : {
        "operationId" : "createPlayer",
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "schema" : {
            "$ref" : "#/definitions/player-complete-data"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/player-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "ut commodo",
                "name" : "magna fugiat in aute officia",
                "email" : "joTDC3FEKT@toz.uwj",
                "password" : "elit",
                "createdOn" : "1940-12-30T21:33:07.821Z",
                "updatedOn" : "1948-08-09T19:56:06.657Z",
                "friends" : [ {
                  "id" : "minim veniam al"
                }, {
                  "id" : "cupidatat magna mollit sint"
                }, {
                  "id" : "dolore"
                }, {
                  "id" : "aliquip amet"
                } ]
              }
            }
          }
        },
        "tags" : [ "player" ]
      }
    },
    "/players/{id}" : {
      "parameters" : [ {
        "name" : "id",
        "in" : "path",
        "type" : "string",
        "required" : true
      } ],
      "get" : {
        "operationId" : "getPlayer",
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/player-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "ut commodo",
                "name" : "magna fugiat in aute officia",
                "email" : "joTDC3FEKT@toz.uwj",
                "password" : "elit",
                "createdOn" : "1940-12-30T21:33:07.821Z",
                "updatedOn" : "1948-08-09T19:56:06.657Z",
                "friends" : [ {
                  "id" : "minim veniam al"
                }, {
                  "id" : "cupidatat magna mollit sint"
                }, {
                  "id" : "dolore"
                }, {
                  "id" : "aliquip amet"
                } ]
              }
            }
          }
        },
        "tags" : [ "player" ]
      },
      "put" : {
        "operationId" : "updatePlayer",
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "schema" : {
            "$ref" : "#/definitions/player-partial-data"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "schema" : {
              "$ref" : "#/definitions/player-complete-data"
            },
            "examples" : {
              "application/json" : {
                "id" : "ut commodo",
                "name" : "magna fugiat in aute officia updated",
                "email" : "joTDC3FEKT@toz.uwj",
                "password" : "elit",
                "createdOn" : "1940-12-30T21:33:07.821Z",
                "updatedOn" : "1948-08-09T19:56:06.657Z",
                "friends" : [ {
                  "id" : "minim veniam al"
                }, {
                  "id" : "cupidatat magna mollit sint"
                }, {
                  "id" : "dolore"
                }, {
                  "id" : "aliquip amet"
                } ]
              }
            }
          }
        },
        "tags" : [ "player" ]
      },
      "delete" : {
        "operationId" : "deletePlayer",
        "responses" : {
          "204" : {
            "description" : "Successfully delete"
          }
        },
        "tags" : [ "player" ],
        "security" : [ {
          "write-auth" : [ ]
        } ]
      }
    }
  },
  "definitions" : {
    "game-partial-data" : {
      "title" : "Game Partial Data",
      "description" : "The properties that are shared amongst all versions of the Game model.",
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid"
        }
      }
    },
    "game-complete-data" : {
      "title" : "Game Complete Data",
      "description" : "The properties that are allowed when creating or updating a Game.",
      "allOf" : [ {
        "$ref" : "#/definitions/game-partial-data"
      }, {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "moves" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "xPos" : {
                  "type" : "integer",
                  "format" : "int32",
                  "minimum" : 1,
                  "maximum" : 9
                },
                "xPlayer" : {
                  "$ref" : "#/definitions/player-partial-data"
                },
                "yPos" : {
                  "type" : "integer",
                  "format" : "int32",
                  "minimum" : 1,
                  "maximum" : 9
                },
                "yPlayer" : {
                  "$ref" : "#/definitions/player-partial-data"
                }
              },
              "required" : [ "xPlayer", "yPlayer" ]
            }
          },
          "result" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "winner" : {
                  "$ref" : "#/definitions/player-partial-data"
                },
                "loser" : {
                  "$ref" : "#/definitions/player-partial-data"
                }
              }
            }
          },
          "status" : {
            "type" : "string",
            "enum" : [ "started", "in progress", "ended" ]
          },
          "session" : {
            "type" : "string",
            "format" : "uri"
          }
        },
        "required" : [ "name" ]
      } ]
    },
    "player-complete-data" : {
      "title" : "Player Complete Data",
      "description" : "The properties that are shared amongst all versions of the Player model.",
      "allOf" : [ {
        "$ref" : "#/definitions/player-partial-data"
      }, {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string",
            "format" : "email"
          },
          "password" : {
            "type" : "string",
            "format" : "password"
          },
          "createdOn" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updatedOn" : {
            "type" : "string",
            "format" : "date-time"
          },
          "friends" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/definitions/player-partial-data"
            }
          }
        }
      } ]
    },
    "player-partial-data" : {
      "title" : "Player Partial Data",
      "description" : "The properties that are shared amongst all versions of the Player model.",
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid"
        }
      }
    }
  },
  "securityDefinitions" : {
    "read-auth" : {
      "type" : "apiKey",
      "name" : "api_key",
      "in" : "header",
      "description" : "API key is needed for reading the data"
    },
    "write-auth" : {
      "type" : "oauth2",
      "flow" : "accessCode",
      "authorizationUrl" : "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl" : "https://accounts.google.com/o/oauth2/token",
      "description" : "oAuth is needed for writing the data",
      "scopes" : {
        "write:game" : "Create or update game data",
        "write:player" : "Create or update player data"
      }
    }
  },
  "basePath" : "/v1",
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "security" : [ {
    "read-auth" : [ ]
  }, {
    "write-auth" : [ ]
  } ],
  "tags" : [ {
    "name" : "game",
    "description" : "Organizes game APIs"
  }, {
    "name" : "player",
    "description" : "Organizes game APIs"
  } ]
}